# Generated by Django 4.2.4 on 2024-09-02 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='status',
            field=models.CharField(choices=[('Active', 'active'), ('Inactive', 'inactive'), ('Pending', 'pending'), ('On Hold', 'on hold'), ('Closed', 'closed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.account'),
        ),
    ]
