# Generated by Django 5.1.1 on 2024-09-17 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_transaction_tr_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='tr_status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Confirmed', 'confirmed'), ('Rejected', 'rejected')], default='Pending', max_length=55),
        ),
    ]
