# Generated by Django 4.2.4 on 2024-08-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('User', 'user'), ('Staff', 'staff'), ('Admin', 'admin')], default='User', max_length=20),
        ),
    ]
