# Generated by Django 4.2.4 on 2024-08-31 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_groups_customuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='account_no',
            field=models.CharField(default=2, editable=False, max_length=12, unique=True),
            preserve_default=False,
        ),
    ]
